/**
 * Real Google Gemini AI Vision Scanner for Medicines.
 * Analyzes medicine strips, blister packs, and bottles to extract:
 * - Brand Name
 * - Generic Composition
 * - Expiry Date & Manufacturing Date
 * - Batch Number
 * - MRP in INR
 * - Condition & Packaging type
 */

import { extractExpiryDate } from "./expiryOcr";

export interface GeminiMedicineScanResult {
  medicineName: string;
  genericComposition?: string;
  category: "tablet" | "capsule" | "syrup" | "injection" | "ointment" | "drops" | "other";
  expiryDate: string; // ISO YYYY-MM-DD
  batchNumber?: string;
  mrp?: number;
  estimatedBuybackPrice?: number;
  condition: "sealed" | "opened";
  isExpired: boolean;
  confidence: number;
  rawNotes?: string;
  success: boolean;
  source: "gemini" | "tesseract_fallback";
}

const STORAGE_KEY_GEMINI = "remed_gemini_api_key";

export function getGeminiApiKey(): string | null {
  if (typeof window === "undefined") return process.env.NEXT_PUBLIC_GEMINI_API_KEY || null;
  const stored = window.localStorage.getItem(STORAGE_KEY_GEMINI);
  if (stored && stored.trim()) return stored.trim();
  return process.env.NEXT_PUBLIC_GEMINI_API_KEY || null;
}

export function setGeminiApiKey(key: string): void {
  if (typeof window === "undefined") return;
  if (!key.trim()) {
    window.localStorage.removeItem(STORAGE_KEY_GEMINI);
  } else {
    window.localStorage.setItem(STORAGE_KEY_GEMINI, key.trim());
  }
}

/**
 * Convert base64 dataUrl into mimeType & raw base64 string
 */
function parseDataUrl(dataUrl: string): { mimeType: string; base64Data: string } {
  const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9.+_-]+);base64,(.+)$/);
  if (match) {
    return { mimeType: match[1], base64Data: match[2] };
  }
  // Default fallback
  return { mimeType: "image/jpeg", base64Data: dataUrl };
}

/**
 * Scan medicine image using Google Gemini Multimodal Vision API
 */
export async function scanMedicineWithGemini(
  imageDataUrl: string
): Promise<GeminiMedicineScanResult> {
  const apiKey = getGeminiApiKey();

  // If no Gemini key is provided, gracefully fallback to on-device OCR
  if (!apiKey) {
    return fallbackToLocalOcr(imageDataUrl, "Gemini API key not configured. Used on-device OCR.");
  }

  try {
    const { mimeType, base64Data } = parseDataUrl(imageDataUrl);

    const prompt = `You are a certified pharmacist AI assistant for ReMeD (Certified Medicine Redistribution & Buyback platform).
Carefully analyze this medicine strip, bottle, or packaging image.

Extract all visible pharmaceutical details and return ONLY a valid JSON object matching this schema:
{
  "medicineName": "Full brand name of the medicine (e.g. Dolo 650, Augmentin 625 Duo, Pan 40)",
  "genericComposition": "Active salts and strength (e.g. Paracetamol 650mg, Amoxicillin and Clavulanate Potassium)",
  "category": "tablet" | "capsule" | "syrup" | "injection" | "ointment" | "drops" | "other",
  "expiryMonth": 1-12 (integer month of expiry, e.g. 12),
  "expiryYear": 2024-2035 (4-digit integer year of expiry, e.g. 2026),
  "batchNumber": "Batch or Lot number printed on strip (e.g. BT9823)",
  "mrp": Numerical MRP in Indian Rupees (INR) for the full pack/strip (e.g. 185.50),
  "condition": "sealed" (if all foil pockets are intact and sealed) or "opened" (if tablets were consumed or foil cut),
  "confidence": Confidence between 0.1 and 1.0 (float)
}

Important:
- Read the EXPIRY DATE printed after 'EXP', 'EXPIRY', 'USE BEFORE', or 'MFD'.
- Expiry date is critical for patient safety.
- Return ONLY pure JSON, no markdown codeblocks, no explanations.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                { text: prompt },
                {
                  inlineData: {
                    mimeType: mimeType,
                    data: base64Data,
                  },
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.1,
            responseMimeType: "application/json",
          },
        }),
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.warn("Gemini API call failed:", response.status, errText);
      return fallbackToLocalOcr(imageDataUrl, `Gemini API returned ${response.status}`);
    }

    const data = await response.json();
    const candidate = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidate) {
      return fallbackToLocalOcr(imageDataUrl, "No text generated by Gemini vision");
    }

    const parsed = JSON.parse(candidate);

    // Format Expiry Date to ISO YYYY-MM-DD
    const expYear = Number(parsed.expiryYear) || new Date().getFullYear() + 1;
    const expMonth = Math.min(Math.max(1, Number(parsed.expiryMonth) || 12), 12);
    const lastDayOfMonth = new Date(expYear, expMonth, 0).getDate();
    const isoDate = `${expYear}-${String(expMonth).padStart(2, "0")}-${String(lastDayOfMonth).padStart(2, "0")}`;

    const now = new Date();
    const isExpired = new Date(isoDate) < now;

    // Calculate estimated buyback (50% to 65% of MRP for sealed unexpired packs)
    const mrpNum = Number(parsed.mrp) || 0;
    const estBuyback = mrpNum > 0 ? Math.round(mrpNum * 0.6) : undefined;

    return {
      medicineName: parsed.medicineName || "Unidentified Medicine",
      genericComposition: parsed.genericComposition || "",
      category: validateCategory(parsed.category),
      expiryDate: isoDate,
      batchNumber: parsed.batchNumber || "",
      mrp: mrpNum > 0 ? mrpNum : undefined,
      estimatedBuybackPrice: estBuyback,
      condition: parsed.condition === "opened" ? "opened" : "sealed",
      isExpired,
      confidence: Math.min(Math.max(0.1, Number(parsed.confidence) || 0.9), 1),
      rawNotes: parsed.genericComposition ? `Active: ${parsed.genericComposition}` : undefined,
      success: true,
      source: "gemini",
    };
  } catch (error) {
    console.warn("Error running Gemini vision, falling back to local OCR:", error);
    return fallbackToLocalOcr(imageDataUrl, "Network/parsing error with Gemini Vision");
  }
}

function validateCategory(cat: string): GeminiMedicineScanResult["category"] {
  const valid = ["tablet", "capsule", "syrup", "injection", "ointment", "drops", "other"];
  const lower = (cat || "").toLowerCase();
  if (valid.includes(lower)) {
    return lower as GeminiMedicineScanResult["category"];
  }
  return "tablet";
}

/**
 * On-device fallback OCR using Tesseract.js
 */
async function fallbackToLocalOcr(
  imageDataUrl: string,
  reason: string
): Promise<GeminiMedicineScanResult> {
  try {
    const { recognize } = await import("tesseract.js");
    const result = await recognize(imageDataUrl, "eng");
    const rawText = result?.data?.text || "";

    const detectedExpiry = extractExpiryDate(rawText);
    const now = new Date();
    const isExp = detectedExpiry ? new Date(detectedExpiry) < now : false;

    // Try to guess medicine name from first non-empty uppercase word lines
    const lines = rawText
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.length > 3 && !/batch|mfg|exp|mrp|rs\.|price|tablet|capsule|mg\b/i.test(l));

    const guessedName = lines[0] || "";

    // Try to extract MRP
    const mrpMatch = rawText.match(/M\.?R\.?P\.?[^\d]{0,5}(?:RS\.?)?\s*(\d{2,4}(?:\.\d{2})?)/i);
    const mrp = mrpMatch ? parseFloat(mrpMatch[1]) : undefined;

    // Try to extract Batch
    const batchMatch = rawText.match(/(?:B\.?NO|BATCH(?:\s*NO)?)[.:\s]*([A-Z0-9-]{3,12})/i);
    const batchNumber = batchMatch ? batchMatch[1].trim() : undefined;

    return {
      medicineName: guessedName || "Medicine Strip",
      category: "tablet",
      expiryDate: detectedExpiry || "",
      batchNumber,
      mrp,
      estimatedBuybackPrice: mrp ? Math.round(mrp * 0.55) : undefined,
      condition: "sealed",
      isExpired: isExp,
      confidence: detectedExpiry ? 0.75 : 0.4,
      rawNotes: reason,
      success: !!detectedExpiry || !!guessedName,
      source: "tesseract_fallback",
    };
  } catch (err) {
    console.error("Local OCR fallback failed:", err);
    return {
      medicineName: "",
      category: "tablet",
      expiryDate: "",
      condition: "sealed",
      isExpired: false,
      confidence: 0,
      rawNotes: "OCR failed: " + String(err),
      success: false,
      source: "tesseract_fallback",
    };
  }
}
